# Generated by Django 4.2.1 on 2023-05-14 04:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c053ecd-f85c-4747-bab0-9e0536a6a1f9'), primary_key=True, serialize=False),
        ),
    ]
