# Generated by Django 4.2.1 on 2023-05-14 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08623aa7-6437-4529-bde1-f79af156423a'), primary_key=True, serialize=False),
        ),
    ]
