# Generated by Django 4.2.1 on 2023-05-14 15:26

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_alter_message_created_date_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('29d909cc-9931-4664-a0b2-91ef296b6745'), primary_key=True, serialize=False),
        ),
    ]
