# Generated by Django 4.2.1 on 2023-05-14 15:31

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_alter_message_created_date_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 15, 31, 51, 417673, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d8ab4ce-4af4-4017-a033-7975ec73303e'), primary_key=True, serialize=False),
        ),
    ]
