# Generated by Django 4.2.1 on 2023-05-14 15:34

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_alter_message_created_date_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 15, 34, 56, 32546, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa8becb8-9d5b-4472-9992-55b41b6ee017'), primary_key=True, serialize=False),
        ),
    ]
