# Generated by Django 4.2.1 on 2023-05-14 15:38

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0009_alter_message_created_date_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f146a672-0632-4918-8640-1e9aa1ab106c'), primary_key=True, serialize=False),
        ),
    ]
