# Generated by Django 4.2.1 on 2023-05-14 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0011_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8db85f02-4475-4634-a34d-ca5f8ee69ecc'), primary_key=True, serialize=False),
        ),
    ]
