# Generated by Django 4.2.1 on 2023-05-14 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0012_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='what_is_it',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51d402ee-3202-4e75-bfee-33de4cc7ea33'), primary_key=True, serialize=False),
        ),
    ]
