# Generated by Django 4.2.1 on 2023-05-14 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0013_message_what_is_it_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb3db92b-ec32-4996-854f-50aa77953493'), primary_key=True, serialize=False),
        ),
    ]
