# Generated by Django 4.2.1 on 2023-05-15 04:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0015_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa343e1c-5910-426d-a247-16afe0822253'), primary_key=True, serialize=False),
        ),
    ]
