# Generated by Django 4.2.1 on 2023-05-15 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0016_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('965cdafd-af03-45a2-9b66-d1c77be0a52c'), primary_key=True, serialize=False),
        ),
    ]
