# Generated by Django 4.2.1 on 2023-05-15 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0017_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.UUID('434749a5-45a7-43a2-862c-65f9c0858044'), primary_key=True, serialize=False),
        ),
    ]
